---
kind: pipeline
type: docker
name: test

steps:
  - name: format-check
    image: rust:1.93
    commands:
      - rustup component add rustfmt
      - cargo fmt -- --check

  - name: clippy
    image: rust:1.93
    volumes:
      - name: cargo-registry
        path: /usr/local/cargo/registry
    environment:
      CARGO_BUILD_JOBS: 1
    commands:
      - rustup component add clippy
      - cargo clippy --all-targets --no-deps -- -D warnings

  - name: test
    image: rust:1.93
    volumes:
      - name: cargo-registry
        path: /usr/local/cargo/registry
      - name: cargo-git
        path: /usr/local/cargo/git
      - name: target
        path: /drone/src/target
    environment:
      CARGO_BUILD_JOBS: 1
      CARGO_INCREMENTAL: 0
      RUST_MIN_STACK: 8388608
    commands:
      - echo "Running tests in release mode (optimized for memory)..."
      - cargo test --all --release -- --test-threads=1

volumes:
  - name: cargo-registry
    host:
      path: /tmp/drone-cargo-registry
  - name: cargo-git
    host:
      path: /tmp/drone-cargo-git
  - name: target
    host:
      path: /tmp/drone-target

---
kind: pipeline
type: docker
name: build-and-deploy

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: build-api
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      GHCR_USERNAME:
        from_secret: ghcr_username
      GHCR_TOKEN:
        from_secret: ghcr_token
    commands:
      - echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
      - docker buildx create --use --name drone-builder || true
      - docker buildx build
        --cache-from type=registry,ref=ghcr.io/leocalm/piggypulse-api:buildcache
        --cache-to type=registry,ref=ghcr.io/leocalm/piggypulse-api:buildcache,mode=max
        --tag ghcr.io/leocalm/piggypulse-api:latest
        --tag ghcr.io/leocalm/piggypulse-api:${DRONE_COMMIT_SHA:0:7}
        --push
        .

  - name: build-cron
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      GHCR_USERNAME:
        from_secret: ghcr_username
      GHCR_TOKEN:
        from_secret: ghcr_token
    commands:
      - echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
      - docker buildx create --use --name drone-builder || true
      - docker buildx build
        --cache-from type=registry,ref=ghcr.io/leocalm/piggypulse-cron:buildcache
        --cache-to type=registry,ref=ghcr.io/leocalm/piggypulse-cron:buildcache,mode=max
        --tag ghcr.io/leocalm/piggypulse-cron:latest
        --tag ghcr.io/leocalm/piggypulse-cron:${DRONE_COMMIT_SHA:0:7}
        --file Dockerfile.cron
        --push
        .

  - name: deploy
    image: docker:27-cli
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: app-dir
        path: /app
    environment:
      GHCR_USERNAME:
        from_secret: ghcr_username
      GHCR_TOKEN:
        from_secret: ghcr_token
    commands:
      - echo "🚀 Starting deployment..."
      - apk add --no-cache docker-cli-compose
      - docker compose version
      - echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
      - cd /app/budget
      - docker compose pull budget cron
      - docker compose up -d budget cron
      - docker image prune -af
      - echo "✅ Deployed version ${DRONE_COMMIT_SHA:0:7}"

  - name: notify-success
    image: alpine:latest
    when:
      status:
        - success
    commands:
      - echo "✅ Build ${DRONE_BUILD_NUMBER} completed successfully!"
      - echo "📦 Version ${DRONE_COMMIT_SHA:0:7} deployed to production"

  - name: notify-failure
    image: alpine:latest
    when:
      status:
        - failure
    commands:
      - echo "❌ Build ${DRONE_BUILD_NUMBER} failed!"
      - echo "Commit ${DRONE_COMMIT_SHA:0:7} was not deployed"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: app-dir
    host:
      path: /opt/piggypulse
