---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
  event:
    - push
    - promote
    - rollback

steps:
  - name: deploy
    image: docker:27-cli
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: app-dir
        path: /app
    environment:
      GHCR_USERNAME:
        from_secret: ghcr_username
      GHCR_TOKEN:
        from_secret: ghcr_token
    when:
      branch:
        - main
      event:
        - push
        - promote
        - rollback
    commands:
      - echo "🚀 Starting deployment to production..."
      - apk add --no-cache docker-cli-compose
      - docker compose version
      - echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
      - cd /app/budget
      - docker compose pull budget cron
      - docker compose up -d budget cron
      - docker image prune -af
      - echo "✅ Deployed version ${DRONE_COMMIT_SHA:0:7}"

  - name: notify-success
    image: alpine:latest
    when:
      status:
        - success
      branch:
        - main
      event:
        - push
        - promote
        - rollback
    commands:
      - echo "✅ Build ${DRONE_BUILD_NUMBER} completed successfully!"
      - echo "📦 Version ${DRONE_COMMIT_SHA:0:7} deployed to production"

  - name: notify-failure
    image: alpine:latest
    when:
      status:
        - failure
      branch:
        - main
      event:
        - push
    commands:
      - echo "❌ Build ${DRONE_BUILD_NUMBER} failed!"
      - echo "Commit ${DRONE_COMMIT_SHA:0:7} was not deployed"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: app-dir
    host:
      path: /opt/piggypulse
