-- Add user_id foreign keys to user-related tables

ALTER TABLE account
    ADD COLUMN user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT;

ALTER TABLE category
    ADD COLUMN user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT;

ALTER TABLE vendor
    ADD COLUMN user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT;

ALTER TABLE transaction
    ADD COLUMN user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT;

ALTER TABLE budget
    ADD COLUMN user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT;

ALTER TABLE budget_category
    ADD COLUMN user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT;

ALTER TABLE budget_period
    ADD COLUMN user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT;

ALTER TABLE currency
    ADD COLUMN user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT;
